### ISSUE TITLE
Can't install on 2011 Macbook Pro w/MacOS Sierra 10.12.5

### ISSUE THREAD

**Issue by murjax** [MichaelDimmitt/Aerial_Desktop#12]
I can't set the screensaver on this machine. 
I get a message stating that "it can't be installed on this version of MacOS."

**Comment by MichaelDimmitt** [comment]
Thanks for the feedback, 
I'll do some research and see if I can get it working when I next see you at a meetup.

**Comment by MichaelDimmitt** [comment]
This was resolved yesterday. 

The issue was that the screensaver was installed across all users. 
the screensaver was not uninstalling which was displayed in a notification.

the solution was inputting this line of code into the terminal.
```sudo rm -rf /Library/Screen\ Savers/Aerial.saver/```

enter your credentials.
then uninstall and install.

**Comment by MichaelDimmitt** [comment]
see also #13
