### ISSUE TITLE
Labels Not Showing

### ISSUE THREAD

**Issue by murjax** [MichaelDimmitt/Aerial_Desktop#13]
Labels don't show on my 15" 2015 Retina Screen with MacOS 10.12.4. I've uninstalled and reinstalled multiple times. I can select the checkbox but it doesn't do anything when I save or change screensavers.

**Comment by MichaelDimmitt** [comment]
Thanks for the feedback, 
I'll do some research and see if I can get it working when I next see you at a meetup.

**Comment by MichaelDimmitt** [comment]
@murjax, what exactly happened here that fixed the problem? 
We went into <b>System Preferances -> Desktop and Screensaver -> Screensaver -> 
click Aerial -> click Screensaver Options -> check "Show label for Location"</b>

1) checking ```Library/Screen\ Savers/Aerial.saver/``` at ```/``` and ```~``` 
and removing the file with sudo.
2) Maybe restarting your computer solved the problem.
