### ISSUE TITLE
Ensure wifi connection before performing wifi actions.

### ISSUE THREAD

**Issue by MichaelDimmitt** [MichaelDimmitt/Aerial_Desktop#19]
Ensure wifi connection before performing wifi actions. 
Otherwise operate offline.

<b>solution: </b>
```bash
if curl --silent --head https://github.com/michaeldimmitt/aerial_desktop;  
  then echo Internet status: OK; 
  else echo Internet status: ERROR; 
fi | tail -n 1
```

**Comment by murjax** [comment]
`ioreg -c IO80211Interface | grep IO80211SSID | cut -d " " -f 22`

`IO80211SSID` is the name of your current network. It will be empty if you are not connected to a network or if your wifi is off. You will want to check of the presence of this key to determine if you're connected or not. 

Note: We need to test if this key returns anything when connected to a wired network via ethernet. I suspect it won't and will affect our logic. 

Update: Our answer may lie in IOEthernetInterface. Still need to connect to internet through ethernet to determine the key.

**Comment by MichaelDimmitt** [comment]
Wow, that was fast. Thanks Ryan, Ill take a look at this and send a coded response.

`ioreg -c IO80211Interface | echo line=$(grep IO80211SSID); echo $?`
`ioreg -c IO80211Interface | grep IO80211SSID | echo line=$(cut -d " " -f 22); echo $?`
@murjax, try these out on your terminal! 🔥 🔥 
`zero` will be returned if there is a wifi connection.
`one1`  will be returned if there is no wifi connection.

let me know how your ethernet test turns out!

**Comment by MichaelDimmitt** [comment]
I think Github changed their emoji's 🚀 🎩. But maybe it is just being on a windows machine. 

@murjax, We had discussed that just because your computer knows the name of the router, does not ensure that you can actually ping github.

So, though hardware evaluation was a good decision for monitoring battery level; 
Curling to a website or pinging a website might be the most efficient way to go about solving this deliverable. 

```curl www.github.com/michaeldimmitt/Aerial_Desktop```

**Comment by MichaelDimmitt** [comment]
Was going to wait for @murjax to put it down but I went ahead and  found the implementation.
@murjax, which is the best option? A few of them instead of just one?
<pre>
ping -c 1 www.github.com;
ping -c 4 www.github.com;
ping -c 1 http://www.example.com/
ping -c 1 https://www.example.com/
</pre>

**Comment by MichaelDimmitt** [comment]
0) Prior to download saver saver. check if saver.saver exists.
....... we are waiting on 0.... 😂  this looks the solution.
1) Download screensaver saver.... 
2) the battery thing is not going to remove that file... only a full uninstall will.
