### ISSUE TITLE
Constant popup on iMac

### ISSUE THREAD

**Issue by mteros** [MichaelDimmitt/Aerial_Desktop#32]
The program runs but I keep getting a popup box saying the following: “Aerial Desktop: something went wrong, contact michael; did some bad programming.”  The message would go away and then comes back and so on. When I click on the message it would open up Script Editor but nothing else.

**Comment by MichaelDimmitt** [comment]
Hello @mteros, 
<br>thank you for opening an issue! 

Have no fear about the message displaying for your program. 

You are the first user with a Desktop Computer to contact me using the most recent code-release .

Why is the issue occurring?
The most recent change includes a launch agent to monitor a users battery percentage. 

If your battery power goes below 20 percent then the program shuts off on a laptop. However, it appears your desktop computer does not have an understanding of whether it is charging or not charging. Because it does not have a battery. 

That is super interesting.
I will updates in my plan and actions for resolving your issue on this page.

**Comment by MichaelDimmitt** [comment]
preliminary plan is to remove that notification. 

But, that sounds like a bad plan. 
After all, the catch all else notification led to the discovery of this bug. 

### new plan: 
1) perform an ioreg command to find out if desktop computer. 
2) add additional else if logic ... determining that the computer is a desktop.
3) leave the else statement with message to contact mike which should now never occur.
4) confirm fix with @mteros 

estimated completion date: Sunday October 8th

**Comment by MichaelDimmitt** [comment]
# note to self.
### Firstly, ioreg provides no output on a mac.
`ioreg -n AppleSmartBattery | grep Max`

### Second, possibly this is a solution.
<pre>
-iMac:~ $ ioreg -n AppleIntelCPUPowerManagement | grep Po
    | |   |   +-o PRT0@0  <class AppleMCP79AHCIPort, id 0x1000001d1, registered, matched, active, busy 0 (548 ms), retain 12>
    | |   |   +-o PRT1@1  <class AppleMCP79AHCIPort, id 0x1000001d2, registered, matched, active, busy 0 (166 ms), retain 12>
    | |   |     +-o AirPort_AtherosNewma40  <class AirPort_AtherosNewma40, id 0x10000021c, registered, matched, active, busy 0 (1 ms), retain 12>
      +-o AppleIntelCPUPowerManagement  <class AppleIntelCPUPowerManagement, id 0x100000120, registered, matched, active, busy 0 (599 ms), retain 6>
      | |   "CFBundleIdentifier" = "com.apple.driver.AppleIntelCPUPowerManagement"
      | |   "IOMatchCategory" = "AppleIntelCPUPowerManagement"
      | |   "IOClass" = "AppleIntelCPUPowerManagement"
      | +-o AppleIntelCPUPowerManagementClient  <class AppleIntelCPUPowerManagementClient, id 0x100000126, !registered, !matched, active, busy 0, retain 4>
      | | |   |   +-o IOHIDPointing  <class IOHIDPointing, id 0x100000337, registered, matched, active, busy 0 (0 ms), retain 9>
-iMac:~ $ ioreg -n AppleIntelCPUPowerManagementClient | grep Po
    | |   |   +-o PRT0@0  <class AppleMCP79AHCIPort, id 0x1000001d1, registered, matched, active, busy 0 (548 ms), retain 12>
    | |   |   +-o PRT1@1  <class AppleMCP79AHCIPort, id 0x1000001d2, registered, matched, active, busy 0 (166 ms), retain 12>
    | |   |     +-o AirPort_AtherosNewma40  <class AirPort_AtherosNewma40, id 0x10000021c, registered, matched, active, busy 0 (1 ms), retain 12>
      +-o AppleIntelCPUPowerManagement  <class AppleIntelCPUPowerManagement, id 0x100000120, registered, matched, active, busy 0 (599 ms), retain 6>
      | +-o AppleIntelCPUPowerManagementClient  <class AppleIntelCPUPowerManagementClient, id 0x100000126, !registered, !matched, active, busy 0, retain 4>
      |       "IOClass" = "AppleIntelCPUPowerManagementClient"
      |       "IOMatchCategory" = "AppleIntelCPUPowerManagementDriver"
      |       "IOProviderClass" = "AppleIntelCPUPowerManagement"
      |       "CFBundleIdentifier" = "com.apple.driver.AppleIntelCPUPowerManagementClient"
      | | |   |   +-o IOHIDPointing  <class IOHIDPointing, id 0x100000337, registered, matched, active, busy 0 (0 ms), retain 9>
</pre>
