### ISSUE TITLE
Error, contact Michael

### ISSUE THREAD

**Issue by DieProgrammIDE** [MichaelDimmitt/Aerial_Desktop#43]
Hello, i installed it on Mojave and everything is did was throw up error to contact you and uninstall due to rapid sleep i didn't do

**Comment by MichaelDimmitt** [comment]
See #38
Let me know if it works in a degraded fashion

The link #38 references a release that has the program working.

Let me know if this is confusing I can provide better instructions:

release for the degraded version. 
Try it out, verified working on a Mac Book Air, OS: macOS HighSierra 10.13.6

## Instructions: to download the new release

1) [Click here to Download](https://github.com/MichaelDimmitt/Aerial_Desktop/releases/download/v9.1/Aerial_Desktop.zip)
2) Unzip the downloaded file.
3) hold "ctrl" and Open **Installer** and confirm installation.<br>

I am not releasing the menubar tonight.
Let me know if the degraded version is working for you now. 

Thanks, for the feedback. And the motivation to knock the feature out. 
changes were implemented on this branch:
https://github.com/MichaelDimmitt/Aerial_Desktop/tree/CurrentStableRelease
